// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgvjEden2y8il23Tf2ydq2ONbkfizx_x0',
    appId: '1:874127197853:web:93fd4754c700f271fbf674',
    messagingSenderId: '874127197853',
    projectId: 'mad-app-2d570',
    authDomain: 'mad-app-2d570.firebaseapp.com',
    storageBucket: 'mad-app-2d570.firebasestorage.app',
    measurementId: 'G-2T5FZKXH9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54YtGwaOORFaQoS9ejp51QuDzvo3dnZw',
    appId: '1:874127197853:android:7636c6517804b860fbf674',
    messagingSenderId: '874127197853',
    projectId: 'mad-app-2d570',
    storageBucket: 'mad-app-2d570.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgvjEden2y8il23Tf2ydq2ONbkfizx_x0',
    appId: '1:874127197853:web:a167de31b231d9eefbf674',
    messagingSenderId: '874127197853',
    projectId: 'mad-app-2d570',
    authDomain: 'mad-app-2d570.firebaseapp.com',
    storageBucket: 'mad-app-2d570.firebasestorage.app',
    measurementId: 'G-X6YSJB69GN',
  );
}
